/***
 * THIS FILE IS AUTOMATICALLY GENERATED
 * Do not edit this file. It will be overwritten when the configure script is run.
 ***/

#ifndef CHAMPSIM_CONSTANTS_H
#define CHAMPSIM_CONSTANTS_H
#include "util.h"
#define BLOCK_SIZE 256ul
#define LOG2_BLOCK_SIZE lg2(BLOCK_SIZE)
#define PAGE_SIZE 4096ul
#define LOG2_PAGE_SIZE lg2(PAGE_SIZE)
#define STAT_PRINTING_PERIOD 10000000ul
#define NUM_CPUS 1ul
#define NUM_CACHES 7u
#define NUM_OPERABLES 10u
#define VWQ_ENABLE 1
#define ART_ENABLE 0
#define ART_1B 0
#define ART_LITE 0
#define ART_MM 0
#define ART_CTR_PER_WAY 32
#define HYDRA_ENABLE 0
#define HYDRA_ROW_GROUP_SIZE  16
#define HYDRA_RCC_SETS  4096
#define HYDRA_DO_MITS  1
#define IDEAL_TRACKER 0
#define BLOCKHAMMER 0
#define BH_BASELINE 0
#define RH_THRESHOLD 64
#define RESERVE_RH_CAPACITY 268435456
#define RH_BLAST_RADIUS 1
#define DROP_WB 0
#define DRAM_IO_FREQ 2400ul
#define DRAM_CHANNELS 4ul
#define DRAM_RANKS 1ul
#define DRAM_BANKS 32ul
#define DRAM_ROWS 65536ul
#define DRAM_COLUMNS 128ul
#define DRAM_CHANNEL_WIDTH 4ul
#define DRAM_WQ_SIZE 1024ul
#define DRAM_RQ_SIZE 1024ul
#define tRP_DRAM_NANOSECONDS 12.5
#define tRCD_DRAM_NANOSECONDS 12.5
#define tCAS_DRAM_NANOSECONDS 12.5
#define DBUS_TURN_AROUND_NANOSECONDS 7.5
#endif
